### ISSUE TITLE
Updating CUTLASS

### ISSUE THREAD

**Issue by mnicely** [parasailteam/coconet#5]
Hi, it's very exciting to see cutlass being used. I noticed that you're only using 2.5. I wanted to let you know we are releasing 2.11 next week with many performance improvements. Are you able to share what features in cutlass you're using?

**Comment by abhijangda** [comment]
Hi Matthew,

Yes, we are using an older version of cutlass, but that is just because we haven't had time to catch up with new versions of cutlass. In the project, we need to heavily modify the cutlass to support fine-grained overlapping described in the paper (link available in README.md). We currenlty only care about Tesla V100. Adding A100 support, which is available in recent cutlass version, will be cool but is not required at that point. I think in a few weeks we will update cutlass.
